services:
  # This is a dummy service that will run forever. If you have a service that does run forever (like a database), you can skip this.
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - snippetbox_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
  golang:
    build: .
    command: go run ./cmd/web
    ports:
      - 4000:4000
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
        - action: rebuild
          path: go.mod
volumes:
  snippetbox_pg_data:
