services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: mydb
      POSTGRES_DB: mydb
  web:
    build: .
    command: go run ./cmd/web
    ports:
      - 4000:4000
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
        - action: rebuild
          path: go.mod
volumes:
  pg_data:
    external: true
