services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: secret
  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: mydb
      POSTGRES_DB: mydb
  web:
    build: .
    command: go run ./cmd/web
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
        - action: rebuild
          path: go.mod
volumes:
  pg_data:
    external: true
  redis_data:
    external: true
