services:
  # This is a dummy service that will run forever. If you have a service that does run forever (like a database), you can skip this.
  dummy:
    image: busybox
    command: tail -f /dev/null
  golang:
    build: .
    command: go run ./cmd/web
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
        - action: rebuild
          path: go.mod
